"""add about_image_url to site_settings

Revision ID: d7508c498111
Revises: b77a489190e5
Create Date: 2026-03-19 07:09:28.249196+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7508c498111'
down_revision: Union[str, None] = 'b77a489190e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('about_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'about_image_url')
    # ### end Alembic commands ###
