"""add source to contact_messages

Revision ID: 4dbedd42cbb5
Revises: d7508c498111
Create Date: 2026-03-19 07:20:14.485825+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dbedd42cbb5'
down_revision: Union[str, None] = 'd7508c498111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_messages', sa.Column('source', sa.String(length=50), nullable=False, server_default='contact'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_messages', 'source')
    # ### end Alembic commands ###
